services:
  - type: web
    name: youtify
    env: node
    plan: free
    buildCommand: npm install && pip install yt-dlp
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
